server:
  port: 7401
spring:
  application:
    name: gulimall_product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.220.132:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  global-config:
    db-config:
      table-prefix: pms_